In [17]:
import numpy as np
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
docs = np.array([
        'Pada matahari yang bersinar',
        'Pada cuaca yang dingin',
        'Pada matahari yang bersinar, pada cuaca yang dingin, dan satu dan satu yang dua'])
bag = count.fit_transform(docs)

In [18]:
print(count.vocabulary_)



{'pada': 6, 'matahari': 5, 'yang': 8, 'bersinar': 0, 'cuaca': 1, 'dingin': 3, 'dan': 2, 'satu': 7, 'dua': 4}


In [19]:
print(count.get_feature_names())
a=count.get_feature_names()


['bersinar', 'cuaca', 'dan', 'dingin', 'dua', 'matahari', 'pada', 'satu', 'yang']


In [20]:
import numpy 
print(bag.toarray())
b=bag.toarray()




[[1 0 0 0 0 1 1 0 1]
 [0 1 0 1 0 0 1 0 1]
 [1 1 2 1 1 1 2 2 3]]


In [21]:
import pandas as pd
dfa =pd.DataFrame(data=a)
dfb =pd.DataFrame(data=b,index=["doc1", "doc2","doc3"],columns=[a])
dfb
#count_row = dfb.shape[0]

#count_row

bersinar cuaca dan dingin dua matahari pada satu yang
doc1        1     0   0      0   0        1    1    0    1
doc2        0     1   0      1   0        0    1    0    1
doc3        1     1   2      1   1        1    2    2    3

Kata yang paling besar kata (pada) /term frequency dalam dokumen ketiga,paling sering muncul kata tersebut, tetapi setelah ditransformasi kedalam  tf-idfs, kata tersebut relatif kecil nilai tf-idfnya. Perhatikan kemunculan kata tersebut di  (discriminatory information).

$$\text{idf} (t,d) = log\frac{1 + n_d}{1 + \text{df}(d, t)}$$

Persamaan tf-idf yang diimplementasikan dalam scikit-learn adalah:

$$\text{tf-idf}(t,d) = \text{tf}(t,d) \times (\text{idf}(t,d)+1)$$

kemudian umumnya dinormalisasi term frequenciy sebelum dihitung tf-idfs, ( `TfidfTransformer` menormalisasi secara langsung)

Menggunakan berikut (default untuk scikit learn)

$$v_{\text{norm}} = \frac{v}{||v||_2} = \frac{v}{\sqrt{v_{1}^{2} + v_{2}^{2} + \dots + v_{n}^{2}}} = \frac{v}{\big (\sum_{i=1}^{n} v_{i}^{2}\big)^\frac{1}{2}}$$

Silahkan hitung tf-idf untuk kata `yang` dokumen ke 3

Banyak dokumen ($n_d=3$)




In [22]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True, 
                         norm='l2', 
                         smooth_idf=True)
print(tfidf.fit_transform(count.fit_transform(docs))
      .toarray())
tf=tfidf.fit_transform(count.fit_transform(docs)).toarray()

dfbtf =pd.DataFrame(data=tf,index=["doc1", "doc2","doc3"],columns=[a])


[[0.55847784 0.         0.         0.         0.         0.55847784
  0.43370786 0.         0.43370786]
 [0.         0.55847784 0.         0.55847784 0.         0.
  0.43370786 0.         0.43370786]
 [0.19103892 0.19103892 0.50238645 0.19103892 0.25119322 0.19103892
  0.29671753 0.50238645 0.44507629]]


In [23]:
a=tfidf.fit_transform(count.fit_transform(docs)).toarray()
a.shape
print('tf_idf kata "yang"',a[(2,8)])


tf_idf kata "yang" 0.44507629390649395


In [50]:
import pandas as pd

df = pd.read_csv('preproses.csv', encoding='utf-8')
df.head(5)


tweet  sentiment
0  saya sangat senang sekali kalau ibukota pindah...          1
1  tidak terlalu nikmat kalau dikalimantan, sanga...          0
2        susah transportasi kalau pergi  kalimantan.          0
3                 saya sangat mendukung kalau pindah          1
4              berat ongkos kalau pindah kalimantan.          0

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
bag = count.fit_transform(docs)
print(count.get_feature_names())
a=count.get_feature_names()

['bersinar', 'cuaca', 'dan', 'dingin', 'dua', 'matahari', 'pada', 'satu', 'yang']


In [34]:
df.shape

(6, 2)

In [35]:
import re
def praproses(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)()(?:-)?(?:\)|\(|D|P)',
                           text)
    text = (re.sub('[\W]+', ' ', text.lower()) +
            ' '.join(emoticons).replace('-', ''))
    return text

In [46]:
praproses(df.loc[3, 'tweet'])


'nova arianto timnas seperti dibuat main main padahal mereka dibiayai uang rakyat'

Now let us print the contents of the vocabulary to get a better understanding of the underlying concepts:

In [48]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True, 
                         norm='l2', 
                         smooth_idf=True)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.55847784 0.         0.         0.         0.         0.55847784
  0.43370786 0.         0.43370786]
 [0.         0.55847784 0.         0.55847784 0.         0.
  0.43370786 0.         0.43370786]
 [0.19103892 0.19103892 0.50238645 0.19103892 0.25119322 0.19103892
  0.29671753 0.50238645 0.44507629]]


In [38]:
print(tfidf.fit_transform(count.fit_transform(df.head())).toarray())

[[0. 1.]
 [1. 0.]]


In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True, 
                         norm='l2', 
                         smooth_idf=True)
print(tfidf.fit_transform(count.fit_transform(docs))
      .toarray())
tf=tfidf.fit_transform(count.fit_transform(docs)).toarray()

dfbtf =pd.DataFrame(data=tf,index=["doc1", "doc2","doc3"],columns=[a])
